//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DoAnCS403Q.Module.BusinessObjects.DatPhongKhachSan
{

    [DefaultProperty("name")]
    public partial class Room : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        string froom_type;
        public string room_type
        {
            get { return froom_type; }
            set { SetPropertyValue<string>(nameof(room_type), ref froom_type, value); }
        }
        decimal fprice;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal price
        {
            get { return fprice; }
            set { SetPropertyValue<decimal>(nameof(price), ref fprice, value); }
        }
        string fquantity_person;
        public string quantity_person
        {
            get { return fquantity_person; }
            set { SetPropertyValue<string>(nameof(quantity_person), ref fquantity_person, value); }
        }
        string fstatus;
        public string status
        {
            get { return fstatus; }
            set { SetPropertyValue<string>(nameof(status), ref fstatus, value); }
        }
        [Association(@"Room_ServiceReferencesRoom"), Aggregated]
        public XPCollection<Room_Service> Room_Services { get { return GetCollection<Room_Service>(nameof(Room_Services)); } }
    }

}
