//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace DoAnCS403Q.Module.BusinessObjects.DatPhongKhachSan
{

    public partial class Room_Service : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Room froom_id;
        [Association(@"Room_ServiceReferencesRoom")]
        public Room room_id
        {
            get { return froom_id; }
            set { SetPropertyValue<Room>(nameof(room_id), ref froom_id, value); }
        }
        Service fservice_id;
        [Association(@"Room_ServiceReferencesService")]
        public Service service_id
        {
            get { return fservice_id; }
            set { SetPropertyValue<Service>(nameof(service_id), ref fservice_id, value); }
        }
        double fquantity;
        public double quantity
        {
            get { return fquantity; }
            set { SetPropertyValue<double>(nameof(quantity), ref fquantity, value); }
        }
        decimal fprice;
        public decimal price
        {
            get { return fprice; }
            set { SetPropertyValue<decimal>(nameof(price), ref fprice, value); }
        }
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        [PersistentAlias("ToDecimal([quantity]) * [price]")]
        public decimal total_price
        {
            get { return (decimal)(EvaluateAlias(nameof(total_price))); }
        }
    }

}
